### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by ramunasd** [ramunasd/osmctools#1]
@marqqs I suspect You are owner of these all tools. As i now, gitorious service is acquired by gitlab and your original repository does not works.

I think would be fair to transfer this repo to you.

**Comment by marqqs** [comment]
Hi & thanks for the offer! However Gitorious still works fine – and will do this until end of May 2015. There is a semi-automatic migration to Gitlab.

**Comment by ramunasd** [comment]
I see there was changed repo url. Thats why i tought your work was abondoned.
