### ISSUE TITLE
Where is the latest version - here or in gitlab?

### ISSUE THREAD

**Issue by OnkelTem** [ramunasd/osmctools#4]
So which repository is the official, this one or https://gitlab.com/osm-c-tools/osmctools?
Please clarify.
Also, it would be great to reflect this in the `README.md`.

**Comment by ramunasd** [comment]
It's unclear whether official repository exists at all. Latest code can be obtained directly from @marqqs website.
It's in readme already - https://github.com/ramunasd/osmctools/blame/master/README.md#L13
