### ISSUE TITLE
Create an Automated Build on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [ramunasd/osmctools#6]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags from git tags & branches.
Also, since documentation includes an example ```docker run``` command, this would make it run (now it fails unless the build instructions are followed). Thus the ```docker run``` command would become the canonical, no-install-needed way to run latest osmctools.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags.
Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.

Docker search command clearly displays ABs when listing images (mine is also listed):
```
$ docker search osmctools
NAME                  DESCRIPTION                             STARS     OFFICIAL   AUTOMATED
michelesr/osmctools   OSM file manipulation tools             0                    [OK]
pataquets/osmctools   osmctools                               0                    [OK]
tobilg/osmctools      Slim Docker image for using osmctools   0                    [OK]
```
Just a free Docker Hub account and a quick setup would do. Ping me if you need help.

**Comment by ramunasd** [comment]
Thanks Alfonso, i set up AB and everything looks fine except image size - 528Mb looks way too much for several simple tools.
https://hub.docker.com/r/ramunasd/osmctools/

**Comment by pataquets** [comment]
For the local dev/testing workflow, the size is not a problem, since the main point is to build locally, so no issuea about file download.
On the other hand, as a distribution method, I agree that it can be an issues, albeit lesser if you have other images based on the same parent image, due to Docker images layered filesystem approach, which would share common layers with existing and already downloaded images. Also, to improve image size, the Dockerfile could be modified to use multi-stage builds to result in a smaller image.
But again, for the local workflow it would be useless (and perhaps harmful). Maintaining both approaches in separate Dockerfiles would be cumbersome.
It's a matter of proritizing which use case is to be favoured. Each one has it's own tradeoffs. As I see it, image size is not an issue if the distributable is considered a "fat" daily build. People wanting a "slim" image can create a multi-stage image, based on your "fat" daily build and avoid you the trimming/slim down issues (dependencies, missing libs, etc.).
I would recommend to sticking to current (fat) build. Anyway, now you know the tradeoffs.
